### ISSUE TITLE
Ocena aplikacja

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-ios#129]
Po 3 skanowaniach należy wyświetlić użytkownikowi zapytanie o ocenę aplikacji.

**Comment by jakub-kalamarz** [comment]
Cześć, chętnie podjął bym się tego tematu. 

Liczbę udanych skanów zapisywać w user defaults?

**Comment by WezSieTato** [comment]
Hej. Przyjąłbym, że muszą być to skanowania w czasie jednego włączenia aplikacji, wtedy wystarczy że będziemy to trzymać w zmiennej. Jak będę miał chwilę to podrzucę eventy do logowania w ramach zadania.

**Comment by jakub-kalamarz** [comment]
@WezSieTato 
Czy w tej implementacji mogę wykorzystać:
[https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview](requestReview())

I czy wg. HIG najlepszym momentem na takie zapytanie nie było by zwinięcie karty przy liczbie otwartych kart większej lub równiej niż 3?

**Comment by WezSieTato** [comment]
> Czy w tej implementacji mogę wykorzystać:
> https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview

Jak najbardziej :)

> I czy wg. HIG najlepszym momentem na takie zapytanie nie było by zwinięcie karty przy liczbie otwartych kart większej lub równiej niż 3?
 
Takie rozwiązanie brzmi super :)
