### ISSUE TITLE
Brak zdjęć w zgłoszeniu błędu

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-ios#155]
Z jakiegoś powodu zdjęcia nie dochodzą po wysłaniu raportu

**Comment by MatPerowicz** [comment]
@WezSieTato nieaktualne, od kilku dni zdjęcia działają!

![image](https://github.com/KlubJagiellonski/pola-ios/assets/52166969/77afb594-15d0-41c0-8b7e-446f2383faa9)

**Comment by MatPerowicz** [comment]
Zakończone
