### ISSUE TITLE
Generacja mockow

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-ios#187]
Integracja genratora mocków https://github.com/stanfy/SwiftyMock by nie trzeba było ręcznie pisać pustych mocków na potrzeby testów.

**Comment by WezSieTato** [comment]
SwiftyMock wygląda na nie wspierany. Po szybkim rozpoznaniu widzę 2 opcje:
https://github.com/Brightify/Cuckoo
- łatwy w instalacji
https://github.com/birdrides/mockingbird
- instalacja wymaga trochę więcej niż `pod install` 
- dużo szybszy od cuckoo

**Comment by michalnowak061** [comment]
Lepsza opcja: https://github.com/krzysztofzablocki/Sourcery

**Comment by WezSieTato** [comment]
I w tym kierunku właśnie idziemy :)
