### ISSUE TITLE
Wyłączyć kompresję obrazków do uczeni Poli

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-ios#20]
Obrazki do uczenia Poli powinny mieć 100% jakości. Nie kompresujemy w ogólę.

**Comment by paweljaneczek** [comment]
@jakublipinski sprawdź obrazki z 23:33 i 23:38. Pierwsze z nich było zrobione z kompresją 90% JPEG, a drugie z 100% JPEG.
Różnica w wielkości plików jest ogromna (5x większy 100%), a jakość prawie identyczna.
Wydaję mi się, że nie ma sensu ustawiać 100%, 6x600KB=3,6MB to jak na polskie warunki bardzo dużo do uploadu (szczególnie w hipermarketach gdzie często jest słaba sieć)

Na razie wypusciłem zmiany z 90%. Jeżeli to jest ok to zamknij issue. Jeżeli nie to napisz komentarz ;)

**Comment by jakublipinski** [comment]
Jest na ten temat paper (https://arxiv.org/pdf/1604.04004.pdf). Faktycznie poziom 90 jest wystarczający. Zamykam.
