### ISSUE TITLE
Logowanie błędów do firebase crashlitycs

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-ios#211]
Mamy funkcję `BPLog`, która aktualnie tylko printuje do konsoli. Dobrze by było mieć te logi w przypadku crashu. Firebase może zbierać różne rzeczy i przekazać je razem crashem. https://firebase.google.com/docs/crashlytics/customize-crash-reports?hl=en

**Comment by czater** [comment]
W sensie dodać zmodyfikować BP tak:

>func BPLog(_ message: String, file: StaticString = #file, function: StaticString = #function, line: UInt = #line) {
       print("\(message) [\(file)] [\(function)] [\(line)]")
       Crashlytics.crashlytics().log(message)
}

**Comment by WezSieTato** [comment]
Generalnie tak, ale:
 - `Crashlytics.crashlytics().log(message)` loguje i tak do konsoli
 - Crashlitycs jest konfigurowany tylko dla wersji do appstora, trza więc dodać jakiegoś ifa.
 Zacząłem już przy tym dłubać i zrobiłem mały refactor logowania i analityki, jak będę miał chwilę to wrzucą PRa.
