### ISSUE TITLE
Usunąć Fabric.io. Zintegrować Firebase Analytics.

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-ios#22]
Usunąć Fabric.io.

Dodać Firebase do Androida:
https://console.firebase.google.com/u/0/project/pola-8682d/settings/general/ios:com.kj.Pola
(Pliku z kluczem prywatnym nie dodajemy do GitHub'a!)

Integrujemy Crash Reporting:
https://firebase.google.com/docs/crash/ios

Lista wydarzeń do dodania (https://firebase.google.com/docs/analytics/android/events) jest pod adresem:
https://docs.google.com/spreadsheets/d/1fqoX2H2P9wUwLRQiRoKljkEVEIG6Jkre-j_mvtrbI3M/edit#gid=0

**Comment by paweljaneczek** [comment]
@jakublipinski mógłbyś dać dostęp do Firebase'a? 

Z tego co czytam to zalecane jest używanie crashlytics do raportowania crashy (patrz https://firebase.google.com/docs/crash/ios `Note: Crashlytics will soon become the primary crash reporter for Firebase. If you aren't already using Crash Reporting to report crashes and non-fatal errors in your app, we recommend using Crashlytics.`). 
Także jeżeli chodzi o crashe to bym został z tym co mamy

**Comment by jakublipinski** [comment]
@paweljaneczek dodałem ciebie i @jerzyKleszcz 

Zależy mi żeby nie mieć dwóch SDK dołączony. Firebase i Fabric to teraz jest to samo (Google kupił Fabric). Robiłby to tak jak opisane tutaj: https://firebase.google.com/docs/crash/ios
Wywalmy Fabric'a w ogóle.

**Comment by jakublipinski** [comment]
Wstrzymujemy temat do czasu aż Google zintegruje w pęłni Fabric z Firebase

**Comment by paweljaneczek** [comment]
Już jest oficjalne wsparcie. Wygląda na to że firebase używa po prostu bibliotek fabrica, takżę nie powinno być większego problemu z integracją.

**Comment by jakublipinski** [comment]
Takie coś przyszło: 

```
Hi Jakub,
--
Back in March, we graduated Firebase Crashlytics out of beta and announced the retirement of Firebase Crash Reporting. We wanted to give you a friendly reminder that on September 9th, 2018, Firebase Crash Reporting will be fully retired and you will no longer have access to that part of the console.
If you haven’t already, be sure to upgrade to Crashlytics and add the Crashlytics SDK to your app(s). We recommend shipping this soon so that you don't have a gap in your crash reporting. Otherwise, you will lose crash reporting functionality for your app(s) on September 9th.
```

**Comment by paweljaneczek** [comment]
@jakublipinski to dotyczy Firebase Crash Reporting którego nigdy nie używaliśmy

**Comment by jakublipinski** [comment]
@WezSieTato testuję tutaj: https://console.firebase.google.com/u/0/project/pola-8682d/analytics/app/android:pl.pola_app/streamview%3Ft=3&params=_u..dataFilters%253Dplatform%252Cios%252CEQ%252CDIMENSION%252C&cs=app.m.streamview.overview&g=1 
Widzę swoją sesję, ale nie widzę event'ów związanych np. z zeskanowaniem kodu. Coś przeoczyłem?

**Comment by jakublipinski** [comment]
Na to wygląda że jest dobrze.
