### ISSUE TITLE
Lampa błyskowa

### ISSUE THREAD

**Issue by dominikzazula** [KlubJagiellonski/pola-ios#25]
Zauważyłem, że po odpaleniu apki i wybraniu doświetlenia poprzez ikonę "błyskawicy", a następnie minimalizacji aplikacji i ponownym jej wybraniu, ikona flash'a jest cały czas aktywna, a lampa się nie świeci. Dopiero ponowne przeklikanie tego przycisku powoduje ponowne włączenie lampy. Telefon iPhone 6s, iOS 10.3.2

**Comment by jakublipinski** [comment]
Naprawione w `1.7`
