### ISSUE TITLE
Test rozpoznawania produktów po zdjęciu

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-ios#28]
Przystępujemy do testów rozpoznawania produktów po zdjęciu - aby sprawdzić jak to będzie działać.

1. Odpal projekt zlokalizowany pod adresem https://github.com/KlubJagiellonski/pola-ai/tree/master/ios_camera. Jest to przykładowy kod z `Tensorflow` pracujący na modelu, który został już wyćwiczony na naszych zdjęciach. Model i listę produktów które jesteśmy w stanie rozpoznać prześlę osobno.

2. Założ nowy `branch` np. `pola-ai` i przełącz się na niego (w między czasie chcemy jeszcze odpalić Polę 1.6 (https://github.com/KlubJagiellonski/pola-ios/milestone/2))

3.  Przenieś przykładowy kod z punktu 1, tak aby odpalał się w głownym ekranie Poli. Wyświetlaj rozpoznane nazwy produktów na ekranie.

4. Rozpoznane nazwy produktów kończą się liczbą, która jest `id` producenta. Musimy znaleźć warunki na podstawie których stwierdzimy, że aplikacja poprawnie rozpoznała producenta po wyglądzie. Trzeba to będzie wyznaczyć eksperymentalnie. Na początek proponuję zrobić wersję, która będzie na ekranie wyświetlać 10 ostatnio rozpoznanych `id` producentów, pod warunkiem, że skuteczność rozpoznania była przynajmniej `95%`. Na tej podstawie wyznaczymy lepsze warunki.

**Comment by jerzyKleszcz** [comment]
Analogicznie jak w projekcie: https://github.com/KlubJagiellonski/pola-ai/tree/master/ios_camera
dodałem zależność ```TensorFlow-experimental``` do Podfile'a.
Pozostałe frameworki, z których korzysta Pola iOS trzymamy w repo; jednak w przypadku ```TensorFlow-experimental``` wolałbym tego uniknąć - cały framework zajmuje ~600 MB.
@paweljaneczek Będzie ok, jeśli po prostu nie dołączę tego jednego frameworka do repo?

**Comment by paweljaneczek** [comment]
Ja bym się trzymał jednego rozwiązania. Trzymanie 600 Mb rzeczywiście nie jest dobrym pomysłem. Także może dodajmy cały katalog podsowy do gitignore. Sprawdź może tylko czy wtedy podsy się budują, bo używamy bardzo starych wersji i może już nie wszystkie są na githubie

**Comment by jerzyKleszcz** [comment]
@paweljaneczek Zgodnie z Twoją sugestią dodałem katalog Pods do gitignore i upewniłem się, że na czysto przechodzi ```pod install```.

Puściłem merge request z całym taskiem - gotowe do sprawdzenia.
