### ISSUE TITLE
Wsparcie iPhone X

### ISSUE THREAD

**Issue by paweljaneczek** [KlubJagiellonski/pola-ios#31]
W tej chwili aplikacja nie wspiera iPhone X i system dodaje 2 czarne paski na dole i na górze.
![image uploaded from ios](https://user-images.githubusercontent.com/2240226/32735748-dbf7824e-c895-11e7-8a7b-0e4ca881c6af.png)

Z rzeczy które trzeba zrobić:
- trzeba przesunąć górne ikony i dolny tekst o wartość `safe area`. 
- jeżeli nagłówek pokazujących się kart producentów będzie mocno zasłonięty trzeba będzie też pokazywać większą cześć karty
- sprawdzić i odpowiednio zmienić inne widoki w aplikacji (menu, wpisywanie kodu, nagrywanie wideo, raportowanie błędu)

**Comment by Rabusek** [comment]
Pozostałe widoki:
![23600048_10211652770607068_758603630_o](https://user-images.githubusercontent.com/10826482/32737803-595c7aaa-c89b-11e7-95ad-9a610071c784.jpg)
![23549779_10211652771127081_1659064554_n](https://user-images.githubusercontent.com/10826482/32737805-5a585a6e-c89b-11e7-8df8-d5292640bdae.jpg)
![23584828_10211652776367212_1875969320_n](https://user-images.githubusercontent.com/10826482/32737806-5ad92086-c89b-11e7-9165-3cfb97f9048e.jpg)
![23574435_10211652776407213_1811073954_n](https://user-images.githubusercontent.com/10826482/32737807-5b571e00-c89b-11e7-893a-998fb5595171.jpg)
![23601966_10211652776687220_1175594786_n](https://user-images.githubusercontent.com/10826482/32737808-5c2cb556-c89b-11e7-803a-6f67563b9587.jpg)

**Comment by jakublipinski** [comment]
Na iPhone XS nie ma już czarnych pasków. Wcięcie na górze ekranu zasłania jednak logo Poli do połowy (tak jak narysowałem na czerwono):
![2019-05-14 17 21 31](https://user-images.githubusercontent.com/1204581/57714323-8cade000-7674-11e9-9c8a-62e81b77f3d5.jpg)
Może moglibyśmy opuścić logo na tych telefonach?

**Comment by jakublipinski** [comment]
Najlepiej byłoby to rozwiązać opuszczając wszystkie ikony niżej na telefonach z wcięciem.

**Comment by jakublipinski** [comment]
Na iPhone XS już jest dobrze.
