### ISSUE TITLE
Przyjaciele Poli

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-ios#32]
* podmienić splash-screen
* w menu jest dodatkowa opcja "Przyjaciele Poli"
* jeśli API zwraca `is_friend` na `true` wtedy wyświetlamy serduszko na tabie (lub zgodnie z projektem jeśli inaczej)
* po otwarciu taba wyświetlamy dodatkowo informację "Ta firma jest przyjacielem Poli. Dowiedz się więcej"
* Po kliknięciu w powyższe otwieramy stronę "Przyjaciele Poli" (tak jak w menu)

**Comment by paweljaneczek** [comment]
@jakublipinski 

> w menu jest dodatkowa opcja "Przyjaciele Poli"
Co ma być tam pokazane? Web view?

> jeśli API zwraca is_friend na true wtedy wyświetlamy serduszko na tabie (lub zgodnie z projektem jeśli inaczej)
Gdzie ma dokładnie być to serduszko? W nagłówce taba po prawej stronie? Mamy do tego assety?

> po otwarciu taba wyświetlamy dodatkowo informację "Ta firma jest przyjacielem Poli. Dowiedz się więcej"
Gdzie ta informacja ma dokładnie być? Na górze, na dole?

> Po kliknięciu w powyższe otwieramy stronę "Przyjaciele Poli" (tak jak w menu)
Czy napis powinien wygląda jak klikalny? (np. niebieski)

Fajnie jakby się udało zamieścić tutaj design, wtedy będzie łatwiej to zrobić

**Comment by jakublipinski** [comment]
czekamy na designy od Przemka. powiedział że dziś się tym zajmie

**Comment by jakublipinski** [comment]
designy już są, @paweljaneczek weźmiesz się za to?

**Comment by paweljaneczek** [comment]
postaram się, chociaż ostatnio bardzo krucho z czasem u mnie

**Comment by jakublipinski** [comment]
Sprawdziłem na kodzie `5904277719045` i działa
