### ISSUE TITLE
Przycisk Klubu Przyjaciół Poli

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-ios#96]
W lewym górnym rogu zastępujemy logo Poli przyciskiem, którzy przenosi użytkownika do zakładki „Przyjaciele Poli”.

![KPPpol](https://user-images.githubusercontent.com/52166969/85605842-da0bc780-b652-11ea-9066-64015123785b.jpg)
![KPPol2](https://user-images.githubusercontent.com/52166969/85605939-f1e34b80-b652-11ea-8079-0c285536c4d8.jpg)

**Comment by WezSieTato** [comment]
W iOS te logo jest na środku. Zmiana dosyć prosta i szybka.
![IMG_903A044D3FA2-1](https://user-images.githubusercontent.com/4258662/85714356-a2e8f500-b6ea-11ea-97f3-d439c09f8de1.jpeg)
