### ISSUE TITLE
Wklejanie kodów kreskowych

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-ios#97]
Jak na screenie. Czy da się wklejać skopiowany wcześniej kod w polu tekstowym.
 
![image](https://user-images.githubusercontent.com/52166969/85608019-f6106880-b654-11ea-97b1-a321713d91ba.png)
![KPPol3](https://user-images.githubusercontent.com/52166969/85608859-c877ef00-b655-11ea-9b9e-f1c9bfcd90e6.jpg)

**Comment by WezSieTato** [comment]
Rzecz jak najbardziej do zrobienia i jestem bardzo za :) Może być problematyczna, ze tego względu, że nie używamy systemowej klawiatury, gdzie mielibyśmy to "za darmo" i trochę czasu może pochłonąć.

**Comment by MatPerowicz** [comment]
Cześć, bardzo Ci dziękuję za obie wiadomości.

Cieszę się, że obie zmiany są do wykonania. Zastanawiam się co wrzucić do
najnowszej aktualizacji, a te rzeczy zgłaszają użytkownicy.

W przybliżeniu ile godzin pracy będzie z tym wklejaniem kodów 😁?

czw., 25 cze 2020, 13:42 użytkownik Marcin Stepnowski <
notifications@github.com> napisał:

**Comment by WezSieTato** [comment]
Z mojej perspektywy od jednego do trzech wieczorów.

**Comment by MatPerowicz** [comment]
Dziękuję bardzo za informację

czw., 25 cze 2020, 15:31 użytkownik Marcin Stepnowski <
notifications@github.com> napisał:
